version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

  gateway-server:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
      - event-server
    networks:
      - app-network
    restart: always
    environment:
      - AUTH_SERVICE_URL=http://auth-server:3001
      - EVENT_SERVICE_URL=http://event-server:3002

  auth-server:
    build:
      context: .
      dockerfile: src/auth/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/reward-event-system
      - JWT_SECRET=jwtsecret
    restart: always

  event-server:
    build:
      context: .
      dockerfile: src/event/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/reward-event-system
    restart: always

volumes:
  mongodb_data:

networks:
  app-network: